name: sudanese_job_finder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  flutter_zoom_drawer: ^3.1.1
  video_player: ^2.6.1
  jwt_decoder: ^2.0.1
  go_router: ^13.1.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  email_validator: ^2.1.17
  awesome_dialog: ^3.1.0
  url_launcher: ^6.0.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  flutter_pdfview: ^1.3.1
  file_picker: ^5.3.3
  path: any
  http: ^0.13.3

  flutter_native_splash: ^2.3.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
flutter_native_splash:
  color: "#ffffff" 
  image: "assets/images/logo.png"
  color_dark: "#000000"
  android: true
  ios: true
  web: false

  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        # - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf
        # - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
